name: Build macOS

on:
  push:
    paths:
      - "mihomo-tray-macos/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Build & Package
        working-directory: mihomo-tray-macos
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Create DMG
        run: |
          hdiutil create -fs HFS+ -srcfolder mihomo-tray-macos/MihomoTray.app -volname MihomoTray MihomoTray.dmg
      - uses: actions/upload-artifact@v4
        with:
          name: MihomoTray
          path: MihomoTray.dmg
